#!/bin/bash

export KEY="$1"
export DIST="$2"
export ARCH="$3"

rm -f $(find dists/$DIST/ -name 'Contents*')
rm -f dists/$DIST/Release
rm -f dists/$DIST/Release.gpg

apt-ftparchive -c apt-ftparchive.conf generate generate-$DIST.conf

apt-ftparchive -c release-$DIST.conf release dists/$DIST/ >| dists/$DIST/Release

gpg --sign --default-key="$KEY" -ba -o dists/$DIST/Release.gpg dists/$DIST/Release

mkdir -p stamps/$DIST/$ARCH
touch stamps/$DIST/$ARCH/deb-archive

